name: Build addon package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Run Makefile
      run: make
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: addon-package
        path: zip/idTip-*.zip
        retention-days: 14
